service: serverless-mongo-booking
frameworkVersion: '3'

useDotenv: true

plugins: 
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  authenticate:
    handler: src/handlers/authenticate.handler
    events:
      - httpApi:
          path: /authenticate
          method: POST
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST
  getAll:
    handler: src/handlers/getAll.handler
    events:
      - httpApi:
          path: /users
          method: GET
  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /users/{email}
          method: GET
  createMovie:
    handler: src/handlers/createMovie.handler
    events:
      - httpApi:
          path: /movies
          method: POST
  getMovies:
    handler: src/handlers/getMovies.handler
    events:
      - httpApi:
          path: /movies
          method: GET
